[package]
name = "signal-with-channel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
crossbeam-channel = "0.5.12"
ctrlc = "3.4.4"
